---
# Simple workflow for deploying static content to GitHub Pages
# Build, lint, status and deploy
name: Custom Deployment

on:
  schedule:
    - cron: '0 6 * * *' # Runs every day at 6am UTC = 8 GMT+1
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
################################
######### Build job  ###########
################################
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v1
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload entire repository
          path: '.'
  ################################
  ########### Linter  ############
  ################################
  #run-lint:
    #needs: build
    #runs-on: ubuntu-latest
    #steps:
      #- name: Checkout code
        #uses: actions/checkout@v3
        #with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          #fetch-depth: 0

      #- name: Lint Code Base
        #uses: github/super-linter@v4
        #env:
          #VALIDATE_ALL_CODEBASE: false
          #DEFAULT_BRANCH: "master"
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ################################
  ########## Status job ##########
  ################################
  report-build-status:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Report build status
        uses: actions/deploy-pages@v1
        with:
          emit_telemetry: true
          timeout: 600000
  ################################
  ######## Deployment job ########
  ################################
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: report-build-status
    runs-on: ubuntu-latest
    steps:       
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
